// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoatKKdvW1YOE06JO1OQ-SZpKnp5Ol0WM',
    appId: '1:562548054083:web:62c23fa7b906e6ac6b9cf6',
    messagingSenderId: '562548054083',
    projectId: 'evrjnergervn433',
    authDomain: 'evrjnergervn433.firebaseapp.com',
    storageBucket: 'evrjnergervn433.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwQOfuWXVA9BrWZCZdK-zr9ghLqj32Y8s',
    appId: '1:562548054083:android:05387dc846d0e5576b9cf6',
    messagingSenderId: '562548054083',
    projectId: 'evrjnergervn433',
    storageBucket: 'evrjnergervn433.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_lZYnjSK5wh0L0ia-z7BaiXe6OMLPyls',
    appId: '1:562548054083:ios:d754c2c495243b376b9cf6',
    messagingSenderId: '562548054083',
    projectId: 'evrjnergervn433',
    storageBucket: 'evrjnergervn433.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_lZYnjSK5wh0L0ia-z7BaiXe6OMLPyls',
    appId: '1:562548054083:ios:d754c2c495243b376b9cf6',
    messagingSenderId: '562548054083',
    projectId: 'evrjnergervn433',
    storageBucket: 'evrjnergervn433.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoatKKdvW1YOE06JO1OQ-SZpKnp5Ol0WM',
    appId: '1:562548054083:web:531848dcce5fbecb6b9cf6',
    messagingSenderId: '562548054083',
    projectId: 'evrjnergervn433',
    authDomain: 'evrjnergervn433.firebaseapp.com',
    storageBucket: 'evrjnergervn433.firebasestorage.app',
  );
}
